packages:
  - apps/*
  - packages/*

injectWorkspacePackages: true

allowBuilds:
  '@google/genai': true
  esbuild: true
  protobufjs: true
  sharp: true

minimumReleaseAgeExclude:
  - tsx@4.23.1
  - '@averyyy/pi-agent-core@0.80.6-piclient.7'
  - '@averyyy/pi-ai@0.80.6-piclient.7'
  - '@averyyy/pi-coding-agent@0.80.6-piclient.7'
  - '@averyyy/pi-tui@0.80.6-piclient.7'
