import "server-only"

import { randomUUID } from "node:crypto"

import { RuntimeRequestError } from "./runtime-error"

/**
 * The update gate is process local on purpose.  The CLI owns the update
 * transaction, while this process only needs a synchronous guard that is
 * shared by route mutations and worker creation.
 */
interface UpdateMaintenanceState {
  active: {
    operationId: string
    phase: "preparing" | "prepared"
    startupVerification: boolean
  } | null
}

declare global {
  var piWebCodexUpdateMaintenance: UpdateMaintenanceState | undefined
}

const UPDATE_BLOCKED_MESSAGE =
  "The WebUI is preparing for an update. Retry after the restart completes."

function initializeState(): UpdateMaintenanceState {
  const existing = globalThis.piWebCodexUpdateMaintenance
  if (existing) return existing

  const startupVerification = process.env.PI_WEB_CODEX_UPDATE_VERIFYING === "1"
  const state: UpdateMaintenanceState = {
    active: startupVerification
      ? {
          operationId:
            process.env.PI_WEB_CODEX_UPDATE_OPERATION_ID ?? randomUUID(),
          phase: "prepared",
          startupVerification: true,
        }
      : null,
  }
  globalThis.piWebCodexUpdateMaintenance = state
  return state
}

// Run synchronously as the module is evaluated.  The candidate process can
// therefore reject mutations and worker activation before its first request.
initializeState()

export function updateMaintenanceState() {
  return initializeState()
}

export function isUpdateMaintenanceActive() {
  return initializeState().active !== null
}

export function updateMaintenanceError() {
  return isUpdateMaintenanceActive() ? UPDATE_BLOCKED_MESSAGE : null
}

export function assertUpdateAllowed() {
  if (isUpdateMaintenanceActive()) {
    throw new RuntimeRequestError("UpdateMaintenance", UPDATE_BLOCKED_MESSAGE)
  }
}

/** Set the gate before any asynchronous busy check begins. */
export function beginUpdatePreparation() {
  const state = initializeState()
  if (state.active) {
    throw new RuntimeRequestError(
      "UpdatePreparationConflict",
      "Another WebUI update preparation is already active."
    )
  }
  const operationId = randomUUID()
  state.active = {
    operationId,
    phase: "preparing",
    startupVerification: false,
  }
  return operationId
}

export function markUpdatePrepared(operationId: string) {
  const active = initializeState().active
  if (!active || active.operationId !== operationId) {
    throw new RuntimeRequestError(
      "UpdatePreparationConflict",
      "The WebUI update preparation was cancelled or superseded."
    )
  }
  active.phase = "prepared"
}

/**
 * Cancel only the operation that owns the gate.  Startup verification is the
 * one exception: its operation ID is intentionally generated by the
 * candidate process, so the authenticated DELETE may omit it.
 */
export function cancelUpdatePreparation(operationId?: string) {
  const state = initializeState()
  const active = state.active
  if (!active) return false
  if (
    operationId !== undefined &&
    operationId.length > 0 &&
    active.operationId !== operationId
  ) {
    throw new RuntimeRequestError(
      "UpdatePreparationConflict",
      "The WebUI update preparation belongs to another operation."
    )
  }
  if (!operationId && !active.startupVerification) {
    throw new RuntimeRequestError(
      "UpdatePreparationConflict",
      "An operation ID is required to cancel WebUI update preparation."
    )
  }
  state.active = null
  return true
}

/**
 * Prepare all app-owned resources for process replacement.  The gate stays
 * held after success; the CLI releases it only when a candidate process has
 * passed its health/database verification.
 */
export async function prepareForUpdate() {
  const operationId = beginUpdatePreparation()

  try {
    const [
      { getRuntimeSupervisor },
      { getShellSupervisor },
      { getMcpService },
    ] = await Promise.all([
      import("./runtime-supervisor"),
      import("./shell-supervisor"),
      import("./mcp-service"),
    ])

    // Check every busy source after the synchronous gate is installed.  No
    // worker is stopped until all checks pass, so a 409 is side-effect free.
    getShellSupervisor().assertUpdateIdle()
    getRuntimeSupervisor().assertUpdateIdle()
    getMcpService().assertUpdateIdle()

    await getRuntimeSupervisor().drainForUpdate()
    await getMcpService().shutdownForUpdate()
    markUpdatePrepared(operationId)
    return { ok: true, operationId }
  } catch (error) {
    // Preparation never switches the process itself.  Release the gate on
    // every failure so a failed preflight cannot wedge the current process;
    // the CLI may still issue its authenticated DELETE as an idempotent
    // cleanup step.  Busy checks happen before draining, so a 409 remains
    // side-effect free.
    cancelUpdatePreparation(operationId)
    throw error
  }
}

/** Test-only reset hook; production callers should use the authenticated API. */
export function resetUpdateMaintenanceForTests() {
  initializeState().active = null
}
